### ISSUE TITLE
Docker python container is destroyed immediately after its creation

### ISSUE THREAD

**Issue by qingzma** [ucbrise/clipper#263]
I define a function(called _deploy_linear_regression()_ ) in a self-defined python module to deploy python regression models.

If I call this function within the module, everything works fine.
However, if I dont call this function within the module, but import this python module in jupyter notebook and call this function, say, _module_name.deploy_linear_regression()_, then the python docker container is destroyed immediately after its creation.

**Comment by qingzma** [comment]
I think I have figured out what is going wrong.

 it is a personal code mistake when trying to build my own prediction model, which leads to the destruction of the python container immediately after its construction. 

However,  there is no warning to give that hint, but saying the model is deployed successfully! 
And if you call _clipper.get_linked_models()_  in jupyter notebook, you can still get the deployed model.
But if  you call _docker ps_ in the terminal, you cannot see the the container, which means the python container is actually dead, but the code still says the model is deployed successful.

I can get the ID of the dead python container by calling _clipper.get_linked_models()_, then I call _docker logs container_ID_  to find the error.

So maybe this bug should be fixed?

> docker logs d253caff91b0
> First attempting to run Python container without installing supplied dependencies.
> Starting PythonContainer container
> Connecting to Clipper with default port: 7000
> Initializing Python function container
> Traceback (most recent call last):
>   File "/container/python_container.py", line 95, in <module>
>     model = PythonContainer(model_path, input_type)
>   File "/container/python_container.py", line 29, in __init__
>     self.predict_func = load_predict_func(predict_path)
>   File "/container/python_container.py", line 16, in load_predict_func
>     return cloudpickle.load(serialized_func_file)
>   File "/opt/conda/lib/python2.7/pickle.py", line 1384, in load
>     return Unpickler(file).load()
>   File "/opt/conda/lib/python2.7/pickle.py", line 864, in load
>     dispatch[key](self)
>   File "/opt/conda/lib/python2.7/pickle.py", line 1096, in load_global
>     klass = self.find_class(module, name)
>   File "/opt/conda/lib/python2.7/pickle.py", line 1130, in find_class
>     __import__(module)
>   File "/model/modules/ClipperClient.py", line 4, in <module>
>     import Data as dt
>   File "/model/modules/Data.py", line 8, in <module>
>     findspark.init()
>   File "/model/modules/findspark.py", line 121, in init
>     spark_home = find()
>   File "/model/modules/findspark.py", line 32, in find
>     raise ValueError("Couldn't find Spark, make sure SPARK_HOME env is set"

**Comment by Corey-Zumar** [comment]
@qingzma Clipper does not currently prune its connected container registry, so that explains why you still see the ID for the crashed container. However, performance is unaffected: Clipper will not attempt to query a container that is no longer connected.
