### ISSUE TITLE
How to stop specific version of served model ?

### ISSUE THREAD

**Issue by YupaTapuY** [ucbrise/clipper#601]

**Comment by YupaTapuY** [comment]
is there a function that can stop a served model container for specific version, not stop a whole model ?

**Comment by withsmilo** [comment]
@YupaTapuY : 
~I have implemented the function already, but not created it as a PR yet.~

**Comment by withsmilo** [comment]
I'm so sorry about my wrong comment. You can use this API to stop versioned models, 

https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/clipper_admin.py#L1194-L1218

```python
clipper_conn.stop_versioned_models({
            "model_1": ["ver_1"],
            "model_2": ["ver_1", "ver_2"],
        })
```
Please note, however, that this API ONLY deletes them from Docker Orchestration, not Clipper internal.

**Comment by avinregmi** [comment]
@withsmilo  I'm having trouble deleting the model from clipper internal. Is there a way to delete models from clipper internal redis? I've tried deleting application it is linked to but when i'm using get_all_models() it still shows up there even if it does not exist in k8s.

**Comment by withsmilo** [comment]
@avinregmi : My suggestion for API scheme improvement is https://github.com/ucbrise/clipper/issues/603 and current status is here,
* `unlink_model_from_app` API : implemented but not pull-requested yet.
* `unregister_versioned_models` API : implemented and pull-requested already. (https://github.com/ucbrise/clipper/pull/602)
* Rename `delete_application` to `unregister_application` : implemented but not pull-requested yet.

**Comment by withsmilo** [comment]
resolved by #603.
